include: package:lints/recommended.yaml

linter:
  rules:
    - cascade_invocations
    - directives_ordering
    - lines_longer_than_80_chars
    - noop_primitive_operations
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_parenthesis
    - unnecessary_statements
