name: motp
description: A Dart library for generating Mobile-OTP (mOTP) codes.
version: 0.0.1
repository: https://github.com/elliotwutingfeng/motp
funding:
 - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - mfa
  - otp
  - security

environment:
  sdk: ^3.0.0

dependencies:
  hashlib: ^1.13.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.25.3
