name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
          sdk: ['3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Test and generate coverage report
        run: make tests

      - name: Upload coverage to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.sdk == '3.3'
        uses: coverallsapp/github-action@v2

  format-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format Markdown with markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint --disable MD013 MD033 --fix . --ignore CODE_OF_CONDUCT.md --ignore CHANGELOG.md
          git add -A
          git diff --cached --exit-code
